version: '3.4'

volumes:
  data:

networks:
  db:
    driver: bridge
 # queue:

services:
  sql.data:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      # Volume dos dados
      - data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "auth"
    networks:
      - db
 #
 # nosql.data:
 #   image: mongo
 #   networks:
 #     - db
 #
 # memory.data:
 #   image: redis
 #   networks:
 #     - db
 #
 # rabbitmq:
 #   image: rabbitmq
 #   networks:
 #     - queue
 #
  identity.api:
    image: identity.api:${TAG:-latest}
    ports:
      - "5100:80"
    build:
      context: .
      dockerfile: ./src/Identity/Identity.API/Dockerfile    
    environment:
      DB_CONNECTION_STRING: "host=sql.data;port=5432;database=auth;username=postgres;password=postgres"
    networks:
      - db
    depends_on:
      - "sql.data"