version: '3.4'

services:
  sql.data:
    image: postgres

  nosql.data:
    image: mongo

  memory.data:
    image: redis

  rabbitmq:
    image: rabbitmq

  identity.api:
    image: identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: ./src/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data